-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory
(
inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
inv_make character varying NOT NULL,
inv_model character varying NOT NULL,
inv_year character (4) NOT NULL,
inv_description text NOT NULL,
inv_image character varying NOT NULL,
inv_thumbnail character varying NOT NULL,
inv_price numeric (9, 0) NOT NULL,
inv_miles integer NOT NULL,
inv_color character varying NOT NULL,
classification_id integer NOT NULL,
CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

BEGIN;


CREATE TABLE IF NOT EXISTS public.classification
(
    classification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    classification_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

CREATE TABLE IF NOT EXISTS public.inventory
(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    inv_make character varying COLLATE pg_catalog."default" NOT NULL,
    inv_model character varying COLLATE pg_catalog."default" NOT NULL,
    inv_year character(4) COLLATE pg_catalog."default" NOT NULL,
    inv_description text COLLATE pg_catalog."default" NOT NULL,
    inv_image character varying COLLATE pg_catalog."default" NOT NULL,
    inv_thumbnail character varying COLLATE pg_catalog."default" NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying COLLATE pg_catalog."default" NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;